version: '3.1'

services:
  mongo:
    image: mongo
    container_name: docker_mongo
    hostname: mongo
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
      - ./docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"

# TODO: make it work in container connected with mongodb
#  app:
#    build: ./
#    container_name: docker_batchjobs
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo
#    working_dir: /opt/app
#    image: dg-docker-spring-http-alpine-j

