version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: docker_mongo
    hostname: mongo
    volumes:
      - mongodata:/data/db
      - ./docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

volumes:
  mongodata:

# TODO: Not working yet together with mongo. Container cannot communicate to the one with mongo.
#  app:
#    build: ./
#    container_name: docker_batchjobs
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo
#    working_dir: /opt/app
#    image: dg-docker-spring-http-alpine-j

