version: '3.1'

services:
  app:
    build: ./
    container_name: batchjobs
    #image: batch-jobs:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      #- dbpostgresql
      - mongo
    working_dir: /opt/app


  #  dbpostgresql:
  #    image: postgres
  #    container_name: "postgres_db_container"
  #    ports:
  #      - "5432:5432"
  #    environment:
  #      - POSTGRES_PASSWORD=docker
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_DB=batchjobs

  mongo:
    image: mongo
    container_name: mongodb-batchjobs
    hostname: mongodb-batchjobs
    volumes:
      - $HOME/data/mongodb-batchjobs:/data/db
      - $HOME/data/mongodb-batchjobs:/data/bkp
    restart: always
    #    env_file:
    #      - .env
    #      environment:
    #        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
#    command: ["-f", "/etc/mongod.conf"] TODO: create script to create user/pass/db

