version: '3.4'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    networks:
      - gateway
    volumes:
      - mongodata:/data/db
    restart: always
    ports:
      - "27017:27017"

  app:
    build:
      context: ./
    container_name: batch-jobs
    networks:
      - gateway
    depends_on:
      - mongo
    ports:
      - "8080:8080"

networks:
  gateway:
    driver: bridge

volumes:
  mongodata:
