version: '3.1'
services:
  #app:
    #container_name: batch-jobs-postgresql
    #image: app-batch-jobs-postgresql
    #build: ./
    #ports:
    #  - "8080:8080"
    #depends_on:
    #  - dbpostgresql
  dbpostgresql:
    image: postgres
    container_name: "postgres_db_container"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=batch-db
